Data Name                     Format         Type           N-Len  Pos  F-Len
----------------------------- -------------- -------------- ----- ----- -----
Darsp-File-Record                                            2970     1      
Sp-Name-Rows                  OCCURS(99)                              1      
Sp-Name                       x(30)                                   1  2970
                                                                        -----
                                        Total              2970
